
name: 'open PR'
description: 'Checks for android platform'
inputs:
  token:
    description: 'the token that will be used for the api call'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
  