
name: 'open auto PR'
description: 'open PR from master to all releas* branches'
inputs:
  token:
    description: 'the token that will be used for the api call'
    required: true
    
runs:
  using: 'node16'
  main: 'dist/index.js'
  