name: CI
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      component:
        required: true
        type: choice
        options:
          # MVA REPOS START
          - 'A'
          - 'b'
          - 'c'
          # MVA REPOS END


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

     - name: Checkout code
       uses: actions/checkout@v2
     - name: Create Pull Request
       uses: mo3ta-dev/PlayWithGihubActions/openPR@main
       with: 
           token: ${{github.token}}
           pr_label: ${{ inputs.pr_label }} 
