name: Auto close 

on:
  pull_request:
    branches: ['master']
    
    
jobs: 
  close: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3 
        
      - name: close 
        uses: imba-tjd/auto-close-pr-action@0.3.1
        with:
          message: 'closed to use other actions'

