name: By Team qqq


on: 
  pull_request: 


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        shell: bash
        run: |
          echo "start 1"
          git fetch origin main
          echo "start 2"
          CHANGED_FILES=$(git diff --name-only origin/main)
          echo "start 3"
          echo "CHANGED_FILES=$CHANGED_FILES"
          echo "changed_files=$CHANGED_FILES" >> GITHUB_OUTPUT
          echo "start 4"
          echo "data ${{env.GITHUB_ENV}}"


      - name: Run Jest tests for related files
        shell: bash
        env: 
            ddd: changed-files.outputs.changed_files
        run: |
          changed_files=${{env.ddd}}
          echo "$changed_files ,, $CHANGED_FILES"
