name: By Team q


on: 
  pull_request: 


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        shell: bash
        run: |
          echo "CHANGED_FILES=$CHANGED_FILES"
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main)
          echo "CHANGED_FILES=$CHANGED_FILES"

      - name: Run Jest tests for related files
        shell: bash
        run: |
          changed_files=$(echo $CHANGED_FILES)
