name: Create Pull Request 2

on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        type: choice
        options:
          - 'Android'
          - 'iOS'
          - 'React-Native'
      component:
        required: true
        type: choice
        options:
          - 'MVA10'
          - 'MVA10-Framework'
          - 'MVA10-Foundation'
          - 'MVA10-Login'
          - 'MVA10-Message-Center'
          - 'MVA10-Onboarding'
          - 'MVA10-Billing'
          - 'MVA10-Netperform'
          - 'MVA10-SOHO-Billing'
          - 'MVA10-SOHO-Framework'
          - 'MVA10-Purchase'
          - 'MVA10-eSIM'
          - 'MVA10-Roaming'
          - 'MVA12-Framework'
          - 'Netperform-SDK'
          - 'Roaming-SDK'
      branch:
        required: true
        type: choice
        options:
          - 'develop-test'
          - 'test-stage'
          - 'stage-production'

permissions:
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pull request
        uses: mo3ta-dev/PlayWithGihubActions/createAutoPR@main
        with:
          token: ${{ secrets.ONEPLATFORM_GITHUB_TOKEN }}
          repo_name: ' ${{inputs.source_branch}} - '
          source_target_branch: ${{ inputs.source_branch }}
          pr_label: 'auto-merge'
