name: Create Pull Request with code 

on:
  workflow_dispatch: 
  schedule: 
  - cron: '0 16 * * 2'
    
permissions: 
  pull-requests: write   

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: mo3ta-dev/PlayWithGihubActions/openPR@main
      with: 
        token: ${{github.token}}
        head_branch: 'master'
        base_branch: 'release'
        use_base_variations: 'true'
        pr_body: 'sasasas sasasasa'
