name: Create Pull Request with code 

on:
  workflow_dispatch: 
    inputs:
      source_branch:
        required: true
        type: choice 
        options:
          - 'develop'
          - 'test'
          - 'stage'
          - 'production'
      target_branch: 
        required: true
        type: choice 
        options:
          - 'develop'
          - 'test'
          - 'stage'
          - 'production'
      pr_label:
        required: false
        default: ''

    
permissions: 
  pull-requests: write   

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: mo3ta-dev/PlayWithGihubActions/openPR@main
      with: 
        token: ${{github.token}}
        source_branch: ${{ inputs.source_branch }} 
        target_branch: ${{ inputs.target_branch }} 
        pr_label: ${{ inputs.pr_label }} 
