name: Create Pull Request with code 

on:
  workflow_dispatch: 
  schedule: 
  - cron: '*/3 * * * *'
    
permissions: 
  pull-requests: write   

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: mo3ta-dev/PlayWithGihubActions/openPR@main
      with: 
        token: ${{github.token}}
        head_branch: 'master'
        base_branch: 'release30'
        use_base_variations: 'false'
        pr_body: 'our workflow'
        pr_label: 'auto-merge'
