name: gh 
on:
  pull_request:
  workflow_dispatch:     

jobs:
  triage:
    if: github.event.pull_request.user.login != 'octobot'
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3 
        
      - name: git fetch 
        run:  git fetch
      - name: git branch -r
        run:  git branch -r
      - name: git checkout test
        run:  git checkout test
        
      - name: "Comment about changes we can't accept"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          git fetch 
          git branch -r
          git checkout test
          echo "$random()" -> a.txt 
          git add . 
          git commit -m "add .. "
          git push
          gh pr create -B test -h main -t "Merge develop into test" --head
          gh pr edit $PR --add-label 'auto-merge'
          gh pr comment $PR --body 'It looks like you edited `package*.json`, `.github/CODEOWNERS`, or `.github/workflows/**`. We do not allow contributions to these files. Please review our [contributing guidelines](https://github.com/octo-org/octo-repo/blob/main/CONTRIBUTING.md) for what contributions are accepted.'
