name: My Kotlin

on: 
  push: 
    paths:
      - '**/*.kt'
      - '!**/src/*[tT]est*/**'



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get changed files
      run: |
        echo "test is found but not in test, ${{ github.event.ref}}"
