name: My Kotlin

on: 
  push: 
    paths:
      - '**/src/*test*/**'
      - '**/src/*Test*/**'
      



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get changed files
      run: |
        echo "test is found but not in test, ${{ github.event.ref}}"
