name: My Kotlin

on: 
  push: 
    paths-ignore:
      - '**/src/*test*/**'



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get changed files
      run: |
        echo "test is found but not in test"
