name: My Workflow

on: 
  push: 
    paths:
      - '**/workflows/*.yml'
      - '!**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get changed files
      run: |
        echo "yml"
