name: gh 
on:
  pull_request:
  workflow_dispatch:     

jobs:
  triage:
    if: github.event.pull_request.user.login != 'octobot'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: init git 
        run: git init 
      - name: "Comment about changes we can't accept"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit $PR --add-label 'invalid'
          gh pr comment $PR --body 'It looks lpted.'
