name: My WWWWW

on: [push, workflow_dispatch]
     
jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['Android', 'iOS', 'React-Native']
        repo: ['A', 'B', 'C', 'D', 'E']
    steps:
      - name: Print OS and Node Version
        run: |
          echo "Running on ${{ matrix.platform }} with Node.js version ${{ matrix.repo }}"        
