name: AutoMergeFramewroks

on: 
   workflow_dispatch: 
     inputs:
       branch:
          type: choice
          options:
               - 'develop-test'
               - 'support-develop'
               - 'support-hotfix'
    
jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['Android', 'iOS', 'React-Native']
        repo: ['MVA10-Framework','MVA10-Foundation', 'MVA10-Login','MVA10-Message-Center','MVA10-Onboarding','MVA10-Billing','MVA10-Netperform','MVA10-SOHO-Billing','MVA10-SOHO-Framework','MVA10-Purchase', 'MVA10-eSIM', 'MVA10-Roaming', 'MVA12-Framework', 'Netperform-SDK', 'Roaming-SDK']
    steps:      
     - name: Split branches
       run: |
          branches="${{ inputs.branch }}"
          branches_list=(${branches//-/ })
          echo "source=${branches_list[0]}" >> $GITHUB_ENV
          echo "target=${branches_list[1]}" >> $GITHUB_ENV
          
     - name: Run Action on
       run: |
          echo "${{ matrix.platform }}-${{ matrix.repo }} "   
          echo " ${{env.source}} to ${{env.target}}"
