name: workflowA(revert)

on: 
  - push
  - pull_request
  - pull_request_target 

jobs:
  workOnNonRevert: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Run a command
      run: echo "Workflow A"
      if: "!startsWith(github.event.pull_request.title, 'revert')"

    - name: sasasa
      run: echo "sasa"  
  
  
  displayData: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3 
      
    - name: Echo GitHub object
      run: echo "${{ toJson(github.event) }}"
      
    - name: Echo pull_request number
      run: echo "$(jq '.pull_request.number' $GITHUB_EVENT_PATH)"
      
    - name: branches  
      run: git branch -r
