name: Run Every Hour

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  ten-minute-job:
    runs-on: ubuntu-latest

    steps:
    - name: Run Something
      run: echo "This workflow ran on GitHub Actions at $(date +%Y-%m-%d)"
